### ISSUE TITLE
Ability to Finish/Deliver Story with Tracker Resource

### ISSUE THREAD

**Issue by kylegearhart** [concourse/tracker-resource#18]
With the following configuration we've been unable to get our story to be finished. We've triple-checked the Tracker token, project ID, story ID, etc., but to no avail. 

During the running of the job on Concourse, "scanning [Tracker-project-name]" did appear, but then there's no other logs that appear after that. 

Has a situation been encountered like this before? Any ideas what could be wrong?

(Values have been changed for confidentiality)
**pipeline.yml**
```
resources:
- name: app-web-client
  type: git
  source:
    uri: git@github.com:organization/app-web-client.git
    branch: master
    private_key: {{private_repo_key}}
- name: tracker-output
  type: tracker
  source:
    token: {{tracker_api_token}}
    project_id: "12345678"
    tracker_url: https://www.pivotaltracker.com

jobs:
- name: test-web-unit-tests
  plan:
  - get: app-web-client
    trigger: true
  - task: run-unit-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: library/node}
      inputs:
      - name: app-web-client
      run:
        dir: app-web-client
        path: make
        args:
        - unit-tests
  - put: tracker-output
    params:
      repos:
      - app-web-client
```

**credentials.yml**
```
tracker_api_token: 123456789123456789
private_repo_key: [block of key information]
```

**commit message**
```
Test of concourse-tracker integration. [finishes #140470033]
```
